In [1]:
import numpy as np

 (1) 定义一个列表list1=[1,2,4,6,7,8]，将其转化为数组N1

In [2]:
list1 = [1, 2, 4, 6, 7, 8]
N1 = np.array(list1)
print(N1)

[1 2 4 6 7 8]


 (2) 定义一个元组tup1=(1,2,3,4,5,6)，将其转化为数组N2

In [3]:
tup1 = (1, 2, 3, 4, 5, 6)
N2 = np.array(tup1)
print(N2)

[1 2 3 4 5 6]


 (3) 利用内置函数，定义一个1行6列元素全为1的数组N3

In [8]:
N3 = np.ones((1, 6))
print(N3)

[[1. 1. 1. 1. 1. 1.]]


 (4) 将N1，N2，N3垂直连接，形成一个3行6列的二维数组N4

In [5]:
N4 = np.vstack((N1, N2, N3))
print(N4)

[[1. 2. 4. 6. 7. 8.]
 [1. 2. 3. 4. 5. 6.]
 [1. 1. 1. 1. 1. 1.]]


 将N4保存为Python二进制数据文件（.npy格式）

In [6]:
np.save('N4.npy', N4)