In [19]:
import numpy as np
x=np.array([1,2,3,4]).reshape(-1,1)
from sklearn.preprocessing import *
modell=StandardScaler()
modell.fit(x)
m1=modell.transform(x)
model2=MinMaxScaler()
model2.fit(x)
m2=model2.transform(x)
print(m2)

[[0.        ]
 [0.33333333]
 [0.66666667]
 [1.        ]]


In [20]:
x=[1.5,1.7,1.6,2.1,2.2,2.4,2.5,1.8]
y=[2.5,1.3,2.2,6.2,5.2,7.1,9.8,1.9]
x=np.array([x,y]).T
from sklearn.cluster import KMeans
model=KMeans(n_clusters=2,random_state=42)
model.fit(x)
c = model.predict(x)
print(c)

[0 0 0 1 1 1 1 0]


c:\Users\NINGLIK\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\cluster\_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)


In [21]:
import numpy.linalg
A=np.array([[1,-1,1],[2,1,0],[2,1,-1]])
b=np.array([4,3,-1])
x=np.linalg.solve(A,b)
print(x)
A_1=np.linalg.inv(A)
print(A_1)

[1. 1. 4.]
[[ 0.33333333  0.          0.33333333]
 [-0.66666667  1.         -0.66666667]
 [-0.          1.         -1.        ]]


In [22]:
import pandas as pd
df1=pd.DataFrame({'a':[1,-2,np.nan]})
df2=df1.dropna()
df3=df2.sort_values(by='a',ascending=True)
print(df3)

     a
1 -2.0
0  1.0
